-- ============================================================
-- Создаем таблицы, если их нет
-- ============================================================

CREATE TABLE IF NOT EXISTS mpa_ratings (
    mpa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INT NOT NULL CHECK (duration > 0),
    mpa_id BIGINT
);

CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    confirmed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, friend_id),
    CHECK (user_id != friend_id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, genre_id)
);

-- ============================================================
-- Добавляем внешние ключи (если их нет)
-- ============================================================

-- Проверяем, существует ли внешний ключ, и добавляем если нет
ALTER TABLE films ADD FOREIGN KEY (mpa_id) REFERENCES mpa_ratings(mpa_id);
ALTER TABLE likes ADD FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE;
ALTER TABLE likes ADD FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE friends ADD FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE friends ADD FOREIGN KEY (friend_id) REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE film_genres ADD FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE;
ALTER TABLE film_genres ADD FOREIGN KEY (genre_id) REFERENCES genres(genre_id) ON DELETE RESTRICT;

-- ============================================================
-- Заполняем справочники (только если они пустые)
-- ============================================================

-- Вставляем MPA рейтинги только если их нет
INSERT INTO mpa_ratings (mpa_name)
SELECT * FROM (VALUES
    ('G'), ('PG'), ('PG_13'), ('R'), ('NC_17')
) AS vals(name)
WHERE NOT EXISTS (SELECT 1 FROM mpa_ratings WHERE mpa_name = vals.name);

-- Вставляем жанры только если их нет
INSERT INTO genres (genre_name)
SELECT * FROM (VALUES
    ('COMEDY'), ('DRAMA'), ('CARTOON'),
    ('THRILLER'), ('DOCUMENTARY'), ('ACTION_MOVIE')
) AS vals(name)
WHERE NOT EXISTS (SELECT 1 FROM genres WHERE genre_name = vals.name);